version: 2.1

jobs:
  build:
    docker:
      - image: python:3.10.2
        auth:
          username: $USERNAME
          password: $TOKEN
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Activate Environement
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
      - run:
          name: Install Hadolint
          command: |
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64 &&\
              chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./.venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Install Dependencies
          command: |
            . .venv/bin/activate
            make install
      - run:
          name: Run lint
          command: |
            . .venv/bin/activate
            make lint

workflows:
  default:
    jobs:
      - build
