version: 2.1

jobs:
  build:
    docker:
      - image: python:3.10.2
        auth:
          username: $USERNAME
          password: $TOKEN
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Activate Environement
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
      - run:
          name: Install Hadolint
          command: |
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64 &&\
              chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./.venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Install Dependencies
          command: |
            . .venv/bin/activate
            make install
      - run:
          name: Run lint
          command: |
            . .venv/bin/activate
            make lint

  configure:
    docker:
      - image: python:3.7-alpine3.11

    steps:
      - run:
          name: Configure AWS Access Key ID
          command: |
            aws configure set aws_access_key_id \
            $AWS_ACCESS_KEY \
            --profile $PROFILE_NAME
            echo "Print the value for $AWS_PROD_ACCESS_KEY_ID $AWS_PROD_SECRET_ACCESS_KEY"

      - run:
          name: Configure AWS Secret Access Key
          command: |
            aws configure set aws_secret_access_key \
            $AWS_SECRET_KEY \
            --profile $PROFILE_NAME

      - run:
          name: Configure AWS default region
          command: |
            aws configure set region $AWS_DEFAULT_REGION \
            --profile $PROFILE_NAME

  deploy:
    docker:
      - image: python:3.7-alpine3.11
        auth:
          username: $USERNAME
          password: $TOKEN
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --update docker openrc
            pip install awscli
      - run:
          name: Add Connection To AWS
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 908252761198.dkr.ecr.us-east-1.amazonaws.com

workflows:
  default:
    jobs:
      - build
      - configure:
          requires: [build]
      - deploy:
          requires: [configure]
